# Generated by Django 5.2 on 2025-05-05 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=100)),
                ('actividad', models.CharField(max_length=210)),
                ('fecha', models.DateField()),
                ('resultado', models.TextField()),
            ],
        ),
    ]
